/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiarioRouteImport } from './routes/diario'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as HumorRouteImport } from './routes/humor'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as ExercicioSlugRouteImport } from './routes/exercicio.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiarioRoute = DiarioRouteImport.update({
  id: '/diario',
  path: '/diario',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const HumorRoute = HumorRouteImport.update({
  id: '/humor',
  path: '/humor',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicioSlugRoute = ExercicioSlugRouteImport.update({
  id: '/exercicio/$slug',
  path: '/exercicio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/entrar': typeof EntrarRoute
  '/humor': typeof HumorRoute
  '/inicio': typeof InicioRoute
  '/exercicio/$slug': typeof ExercicioSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/entrar': typeof EntrarRoute
  '/humor': typeof HumorRoute
  '/inicio': typeof InicioRoute
  '/exercicio/$slug': typeof ExercicioSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diario': typeof DiarioRoute
  '/entrar': typeof EntrarRoute
  '/humor': typeof HumorRoute
  '/inicio': typeof InicioRoute
  '/exercicio/$slug': typeof ExercicioSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/diario' | '/entrar' | '/humor' | '/inicio' | '/exercicio/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/diario' | '/entrar' | '/humor' | '/inicio' | '/exercicio/$slug'
  id:
    | '__root__'
    | '/'
    | '/diario'
    | '/entrar'
    | '/humor'
    | '/inicio'
    | '/exercicio/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiarioRoute: typeof DiarioRoute
  EntrarRoute: typeof EntrarRoute
  HumorRoute: typeof HumorRoute
  InicioRoute: typeof InicioRoute
  ExercicioSlugRoute: typeof ExercicioSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diario': {
      id: '/diario'
      path: '/diario'
      fullPath: '/diario'
      preLoaderRoute: typeof DiarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/humor': {
      id: '/humor'
      path: '/humor'
      fullPath: '/humor'
      preLoaderRoute: typeof HumorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicio/$slug': {
      id: '/exercicio/$slug'
      path: '/exercicio/$slug'
      fullPath: '/exercicio/$slug'
      preLoaderRoute: typeof ExercicioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiarioRoute: DiarioRoute,
  EntrarRoute: EntrarRoute,
  HumorRoute: HumorRoute,
  InicioRoute: InicioRoute,
  ExercicioSlugRoute: ExercicioSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
